### ISSUE TITLE
meteor not running in folder

### ISSUE THREAD

**Issue by mfhawley** [Brodan/GroupMeteor#2]
when i run "meteor" in command prompt in the folder it says I am not in a meteor project directory... any help?

**Comment by skarrakc** [comment]
@mfhawley -- it is because the author did not put the ".meteor" folder in the Github repository.
Try to follow this tuto and add right packages to your project : https://www.twilio.com/blog/2015/07/building-a-group-messaging-app-with-meteor-mongodb-and-twilio.html
